"""Agregar tabla Instrumentos

Revision ID: 01fc99075b63
Revises: d2249a7c3a6b
Create Date: 2025-04-26 23:16:58.800465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fc99075b63'
down_revision = 'd2249a7c3a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumentos',
    sa.Column('inst_id', sa.Integer(), nullable=False),
    sa.Column('inst_tipo', sa.String(length=50), nullable=False),
    sa.Column('inst_descripcion', sa.Text(), nullable=False),
    sa.Column('inst_evento_fk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('inst_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrumentos')
    # ### end Alembic commands ###
