"""Añadir estado por evento en ParticipantesEventos

Revision ID: 081e818b6b04
Revises: 
Create Date: 2025-04-03 14:41:37.947442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081e818b6b04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.drop_column('par_estado')

    with op.batch_alter_table('participantes_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('par_estado', mysql.ENUM('PENDIENTE', 'ACEPTADO', 'RECHAZADO'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participantes_eventos', schema=None) as batch_op:
        batch_op.drop_column('par_estado')

    with op.batch_alter_table('participantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('par_estado', mysql.ENUM('PENDIENTE', 'ACEPTADO', 'RECHAZADO'), nullable=False))

    # ### end Alembic commands ###
