"""Agrega campos cobro y cupos a Evento

Revision ID: 3b5ce656c58c
Revises: 
Create Date: 2025-03-14 16:43:33.989389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5ce656c58c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobro', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cupos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('cupos')
        batch_op.drop_column('cobro')

    # ### end Alembic commands ###
