"""AGREGUE EL CAMPO IMAGE IN DATABASE

Revision ID: 74a1f4beb6c7
Revises: a473e62d034d
Create Date: 2025-03-26 17:50:32.230146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a1f4beb6c7'
down_revision = 'a473e62d034d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
