"""NUEVOS CAMPOS PARA HABILITAR Y DESHABILITAR FORMS

Revision ID: 89c54e4863f0
Revises: 
Create Date: 2025-04-04 23:54:00.475715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c54e4863f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscripciones_participantes_abiertas', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('inscripciones_asistentes_abiertas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('inscripciones_asistentes_abiertas')
        batch_op.drop_column('inscripciones_participantes_abiertas')

    # ### end Alembic commands ###
