"""Agregando tablas splanning #3 

Revision ID: d2249a7c3a6b
Revises: 
Create Date: 2025-04-25 19:46:10.794420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2249a7c3a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterios',
    sa.Column('cri_id', sa.Integer(), nullable=False),
    sa.Column('cri_descripcion', sa.String(length=100), nullable=False),
    sa.Column('cri_peso', sa.Float(), nullable=False),
    sa.Column('cri_evento_fk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cri_id')
    )
    op.create_table('evaluadores',
    sa.Column('eva_id', sa.String(length=20), nullable=False),
    sa.Column('eva_nombre', sa.String(length=100), nullable=False),
    sa.Column('eva_correo', sa.String(length=100), nullable=False),
    sa.Column('eva_telefono', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('eva_id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cal_evaluador_fk', sa.String(length=20), nullable=False),
    sa.Column('cal_criterio_fk', sa.Integer(), nullable=False),
    sa.Column('cal_participante_fk', sa.String(length=20), nullable=False),
    sa.Column('cal_valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cal_criterio_fk'], ['criterios.cri_id'], ),
    sa.ForeignKeyConstraint(['cal_evaluador_fk'], ['evaluadores.eva_id'], ),
    sa.ForeignKeyConstraint(['cal_participante_fk'], ['participantes.par_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificaciones')
    op.drop_table('evaluadores')
    op.drop_table('criterios')
    # ### end Alembic commands ###
