"""Agregar campo de archivo en eventos PARA LA PROGRAMACION

Revision ID: dbf7fa625db6
Revises: 74a1f4beb6c7
Create Date: 2025-03-30 11:42:52.942582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf7fa625db6'
down_revision = '74a1f4beb6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_programacion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('archivo_programacion')

    # ### end Alembic commands ###
