"""Actualizacion bases de datos

Revision ID: f117105b9a1e
Revises: 3b5ce656c58c
Create Date: 2025-03-17 10:36:25.040499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f117105b9a1e'
down_revision = '3b5ce656c58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caracteristicas')
    op.drop_table('eventos_caracteristicas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_caracteristicas',
    sa.Column('eve_car_evento_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('eve_car_caracteristica_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eve_car_caracteristica_fk'], ['caracteristicas.car_id'], name='eventos_caracteristicas_ibfk_2'),
    sa.ForeignKeyConstraint(['eve_car_evento_fk'], ['eventos.eve_id'], name='eventos_caracteristicas_ibfk_1'),
    sa.PrimaryKeyConstraint('eve_car_evento_fk', 'eve_car_caracteristica_fk'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('caracteristicas',
    sa.Column('car_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('car_parametro', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('car_valor', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('car_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
