"""Añadir LLAVE EVENTOS PARA PODER ASIGNAR UN EVALUADOR A UNO O VARIOS EVENTOS

Revision ID: f18790f0ff2a
Revises: 01fc99075b63
Create Date: 2025-04-28 16:45:19.465203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18790f0ff2a'
down_revision = '01fc99075b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluador_evento',
    sa.Column('evaluador_id', sa.String(length=20), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluador_id'], ['evaluadores.eva_id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.eve_id'], ),
    sa.PrimaryKeyConstraint('evaluador_id', 'evento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluador_evento')
    # ### end Alembic commands ###
